spring.application.name=trixi_task_spring
spring.datasource.url=jdbc:postgresql://localhost:5433/trixi
spring.datasource.username=postgres
spring.datasource.password=trixi

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true