services:
  db:
    image: postgres:18
    container_name: trixi-postgres

    environment:
      POSTGRES_DB: trixi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: trixi

    ports:
      - "5433:5432"

    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql